export async function onRequestOptions() {
  return new Response(null, {
    status: 204,
    headers: corsHeaders(),
  });
}

const SYSTEM_PROMPT = [
  "You are GrowZone AI, a practical business growth strategist for founders and small teams.",
  "Give detailed, structured answers with clear steps, examples, and tradeoffs.",
  "When useful, organize the response into short sections such as Summary, Recommendations, Next Steps, Risks, and Metrics.",
  "Be direct, specific, and actionable. Avoid vague advice.",
  "If the user request is unclear, ask one focused clarifying question instead of guessing.",
].join(" ");

export async function onRequestPost(context) {
  const { request, env } = context;

  try {
    const body = await request.json();
    const prompt = (body?.q || "").toString().trim();

    if (!prompt) {
      return json({ answer: "Please provide a question in field 'q'." }, 400);
    }

    const hfApiKey = env.HF_API_KEY;
    const hfModel = normalizeModel(env.HF_MODEL || "Qwen/Qwen2.5-1.5B-Instruct");

    if (!hfApiKey) {
      return json({ answer: "Missing HF_API_KEY in Cloudflare environment variables." }, 500);
    }

    const response = await fetch("https://router.huggingface.co/v1/chat/completions", {
      method: "POST",
      headers: {
        "Authorization": `Bearer ${hfApiKey}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        model: hfModel,
        messages: [
          { role: "system", content: SYSTEM_PROMPT },
          { role: "user", content: prompt },
        ],
        temperature: 0.5,
        top_p: 0.9,
        max_tokens: 500,
      }),
    });

    const raw = await response.text();
    let data = {};

    try {
      data = JSON.parse(raw);
    } catch {
      data = { raw };
    }

    if (!response.ok) {
      const detail = data?.error?.message || data?.error || raw || `HTTP ${response.status}`;
      return json({ answer: `Hugging Face error: ${detail}` }, response.status);
    }

    const answer = data?.choices?.[0]?.message?.content?.trim();
    return json({ answer: answer || "No response generated by model." }, 200);
  } catch (error) {
    return json({ answer: `Request failed: ${error.message}` }, 500);
  }
}

function normalizeModel(model) {
  return model.includes(":") ? model : `${model}:fastest`;
}

function json(payload, status) {
  return new Response(JSON.stringify(payload), {
    status,
    headers: {
      "Content-Type": "application/json",
      ...corsHeaders(),
    },
  });
}

function corsHeaders() {
  return {
    "Access-Control-Allow-Origin": "*",
    "Access-Control-Allow-Methods": "POST, OPTIONS",
    "Access-Control-Allow-Headers": "Content-Type",
  };
}
