import os
from pathlib import Path
from time import time
from typing import Optional

from flask import Flask, abort, jsonify, request, send_from_directory
from huggingface_hub import InferenceClient
import razorpay

app = Flask(__name__)
ROOT_DIR = Path(__file__).resolve().parents[1]


def load_env_file(env_path: Path) -> None:
    if not env_path.is_file():
        return

    for raw_line in env_path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue

        key, value = line.split("=", 1)
        key = key.strip()
        value = value.strip()
        if key:
            os.environ[key] = value


load_env_file(ROOT_DIR / ".env")


def normalize_model(model: str) -> str:
    return model


DEFAULT_HF_MODEL = "Qwen/Qwen2.5-1.5B-Instruct"
DEFAULT_CURRENCY = "INR"
PRICING_TABLE = {
    "free": {"monthly": 0, "yearly": 0},
    "pro": {"monthly": 2900, "yearly": 27900},
    "premium": {"monthly": 9900, "yearly": 95000},
}
SYSTEM_PROMPT = (
    "You are GrowZone AI, a practical business growth strategist for founders and small teams. "
    "Give detailed, structured answers with clear steps, examples, and tradeoffs. "
    "When useful, organize the response into short sections such as Summary, Recommendations, Next Steps, Risks, and Metrics. "
    "Be direct, specific, and actionable. Avoid vague advice. "
    "If the user request is unclear, ask one focused clarifying question instead of guessing."
)


def ask_hugging_face(prompt: str) -> str:
    # Reload .env on each request so key/model updates apply without shell exports.
    load_env_file(ROOT_DIR / ".env")

    hf_api_key = os.getenv("HF_API_KEY", "").strip()
    hf_model = normalize_model(os.getenv("HF_MODEL", DEFAULT_HF_MODEL).strip() or DEFAULT_HF_MODEL)

    if not hf_api_key:
        return "Missing HF_API_KEY. Set it in your environment before running the server."

    client = InferenceClient(api_key=hf_api_key)
    result = client.chat.completions.create(
        model=hf_model,
        messages=[
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": prompt},
        ],
        max_tokens=500,
        temperature=0.5,
        top_p=0.9,
    )

    if result.choices and result.choices[0].message:
        content = (result.choices[0].message.content or "").strip()
        return content or "No response generated by model."

    return "No response generated by model."


def get_razorpay_client() -> tuple[Optional[razorpay.Client], str, str]:
    load_env_file(ROOT_DIR / ".env")
    key_id = os.getenv("RAZORPAY_KEY_ID", "").strip()
    key_secret = os.getenv("RAZORPAY_KEY_SECRET", "").strip()

    if not key_id or not key_secret:
        return None, key_id, "Missing Razorpay credentials in environment."

    client = razorpay.Client(auth=(key_id, key_secret))
    return client, key_id, ""


@app.post("/query")
def query():
    body = request.get_json(silent=True) or {}
    prompt: Optional[str] = body.get("q")

    if not prompt:
        return jsonify({"answer": "Please provide a question in field 'q'."}), 400

    try:
        answer = ask_hugging_face(prompt)
        return jsonify({"answer": answer})
    except Exception as exc:  # noqa: BLE001
        return jsonify({"answer": f"Request failed: {exc}"}), 500


@app.get("/health")
def health():
    load_env_file(ROOT_DIR / ".env")
    ready = bool(os.getenv("HF_API_KEY", "").strip())
    model = normalize_model(os.getenv("HF_MODEL", DEFAULT_HF_MODEL).strip() or DEFAULT_HF_MODEL)
    razorpay_ready = bool(os.getenv("RAZORPAY_KEY_ID", "").strip() and os.getenv("RAZORPAY_KEY_SECRET", "").strip())
    return jsonify({"status": "ok", "hf_ready": ready, "model": model, "razorpay_ready": razorpay_ready})


@app.get("/api/billing/plans")
def billing_plans():
    return jsonify(
        {
            "currency": DEFAULT_CURRENCY,
            "plans": {
                "free": {"name": "Free", "monthly": 0, "yearly": 0},
                "pro": {"name": "Pro", "monthly": 2900, "yearly": 27900},
                "premium": {"name": "Premium", "monthly": 9900, "yearly": 95000},
            },
        }
    )


@app.get("/api/razorpay/config")
def razorpay_config():
    _, key_id, error = get_razorpay_client()
    return jsonify({"enabled": not bool(error), "key_id": key_id})


@app.post("/api/razorpay/order")
def razorpay_order():
    client, key_id, error = get_razorpay_client()
    if error:
        return jsonify({"error": error}), 500

    payload = request.get_json(silent=True) or {}
    plan = str(payload.get("plan", "")).strip().lower()
    cycle = str(payload.get("billing_cycle", "monthly")).strip().lower()

    if plan not in PRICING_TABLE:
        return jsonify({"error": "Invalid plan selected."}), 400
    if cycle not in {"monthly", "yearly"}:
        return jsonify({"error": "Invalid billing cycle selected."}), 400

    amount = int(PRICING_TABLE[plan][cycle])
    if amount <= 0:
        return jsonify({"error": "Selected plan does not require payment."}), 400

    receipt = f"growzone-{plan}-{cycle}-{int(time())}"
    try:
        order = client.order.create(
            {
                "amount": amount,
                "currency": DEFAULT_CURRENCY,
                "receipt": receipt,
                "notes": {"plan": plan, "billing_cycle": cycle},
            }
        )
    except Exception as exc:  # noqa: BLE001
        return jsonify({"error": f"Unable to create Razorpay order: {exc}"}), 502

    return jsonify(
        {
            "key_id": key_id,
            "order": order,
            "plan": plan,
            "billing_cycle": cycle,
            "amount": amount,
            "currency": DEFAULT_CURRENCY,
        }
    )


@app.post("/api/razorpay/verify")
def razorpay_verify():
    client, _, error = get_razorpay_client()
    if error:
        return jsonify({"error": error}), 500

    payload = request.get_json(silent=True) or {}
    order_id = str(payload.get("razorpay_order_id", "")).strip()
    payment_id = str(payload.get("razorpay_payment_id", "")).strip()
    signature = str(payload.get("razorpay_signature", "")).strip()

    if not order_id or not payment_id or not signature:
        return jsonify({"error": "Missing payment verification fields."}), 400

    try:
        client.utility.verify_payment_signature(
            {
                "razorpay_order_id": order_id,
                "razorpay_payment_id": payment_id,
                "razorpay_signature": signature,
            }
        )
    except Exception as exc:  # noqa: BLE001
        return jsonify({"verified": False, "error": f"Signature verification failed: {exc}"}), 400

    return jsonify({"verified": True, "message": "Payment verified successfully."})


@app.get("/")
def index():
    return send_from_directory(ROOT_DIR, "index.html")


@app.get("/<path:filename>")
def static_files(filename: str):
    if "/" in filename or "\\" in filename or filename.startswith("."):
        abort(404)

    file_path = ROOT_DIR / filename
    if not file_path.is_file():
        abort(404)

    return send_from_directory(ROOT_DIR, filename)


if __name__ == "__main__":
    port = int(os.getenv("PORT", "5000"))
    app.run(host="0.0.0.0", port=port, debug=True)
