import os
from typing import Optional

import requests
from flask import Flask, jsonify, request

app = Flask(__name__)

HF_API_KEY = os.getenv("HF_API_KEY", "")
HF_MODEL = os.getenv("HF_MODEL", "mistralai/Mistral-7B-Instruct-v0.2")
HF_URL = f"https://api-inference.huggingface.co/models/{HF_MODEL}"


def _build_headers() -> dict:
    headers = {"Content-Type": "application/json"}
    if HF_API_KEY:
        headers["Authorization"] = f"Bearer {HF_API_KEY}"
    return headers


def ask_hugging_face(prompt: str) -> str:
    if not HF_API_KEY:
        return "Missing HF_API_KEY. Set it in your environment before running the server."

    payload = {
        "inputs": prompt,
        "parameters": {
            "max_new_tokens": 300,
            "temperature": 0.6,
            "return_full_text": False,
        },
    }

    response = requests.post(HF_URL, headers=_build_headers(), json=payload, timeout=60)
    response.raise_for_status()
    data = response.json()

    if isinstance(data, list) and data and "generated_text" in data[0]:
        return data[0]["generated_text"].strip()
    if isinstance(data, dict) and data.get("error"):
        return f"Hugging Face error: {data['error']}"

    return "No response generated by model."


@app.post("/query")
def query():
    body = request.get_json(silent=True) or {}
    prompt: Optional[str] = body.get("q")

    if not prompt:
        return jsonify({"answer": "Please provide a question in field 'q'."}), 400

    try:
        answer = ask_hugging_face(prompt)
        return jsonify({"answer": answer})
    except Exception as exc:  # noqa: BLE001
        return jsonify({"answer": f"Request failed: {exc}"}), 500


if __name__ == "__main__":
    port = int(os.getenv("PORT", "5000"))
    app.run(host="0.0.0.0", port=port, debug=True)
