import os
from typing import Optional

from flask import Flask, jsonify, request
from huggingface_hub import InferenceClient

app = Flask(__name__)

HF_API_KEY = os.getenv("HF_API_KEY", "")
def normalize_model(model: str) -> str:
    return model


HF_MODEL = normalize_model(os.getenv("HF_MODEL", "Qwen/Qwen2.5-1.5B-Instruct"))
SYSTEM_PROMPT = (
    "You are GrowZone AI, a practical business growth strategist for founders and small teams. "
    "Give detailed, structured answers with clear steps, examples, and tradeoffs. "
    "When useful, organize the response into short sections such as Summary, Recommendations, Next Steps, Risks, and Metrics. "
    "Be direct, specific, and actionable. Avoid vague advice. "
    "If the user request is unclear, ask one focused clarifying question instead of guessing."
)


def ask_hugging_face(prompt: str) -> str:
    if not HF_API_KEY:
        return "Missing HF_API_KEY. Set it in your environment before running the server."

    client = InferenceClient(api_key=HF_API_KEY)
    result = client.chat.completions.create(
        model=HF_MODEL,
        messages=[
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": prompt},
        ],
        max_tokens=500,
        temperature=0.5,
        top_p=0.9,
    )

    if result.choices and result.choices[0].message:
        content = (result.choices[0].message.content or "").strip()
        return content or "No response generated by model."

    return "No response generated by model."


@app.post("/query")
def query():
    body = request.get_json(silent=True) or {}
    prompt: Optional[str] = body.get("q")

    if not prompt:
        return jsonify({"answer": "Please provide a question in field 'q'."}), 400

    try:
        answer = ask_hugging_face(prompt)
        return jsonify({"answer": answer})
    except Exception as exc:  # noqa: BLE001
        return jsonify({"answer": f"Request failed: {exc}"}), 500


if __name__ == "__main__":
    port = int(os.getenv("PORT", "5000"))
    app.run(host="0.0.0.0", port=port, debug=True)
